/**
 * ======================================================================
 * Copyright (C) 2021-2022  Yobny Technology Solutions
 * This file is part of QueueOne project.
 * ======================================================================
 */

import LocalizedStrings from "react-localization";

const queueStoreStrings = new LocalizedStrings({
  en: {
    queueOneHeading: "QueueOne Page",
    tokens: "Booked tokens",
    Date: "Date",
    TimeZone: "Time Zone",
    ok: "OK",
    expired: "expired",
    pleaseLogin: "Please login",
    companyProduct: "Queueone",
    language: "EN",
    logOut: "Sign Out",
    my: "My",
    search: "Search",
    bookings: "Bookings",
    sign: "Sign",
    out: "Out",
    in: "In",
    signIn: "Sign In",
    waitTime : 'Wait Time',
    ms : 'ms',
    swapRequest : 'Swap Request',
    ask : 'Ask Questions',
    FAQ : 'FAQ',
    reach : 'How to Reach',
    terms : 'Terms and Conditions',
    keepThisPage : 'Keep this page open for real-time updates',
    waitTimeMessage : 'Wait-time show in this page is indicative and near real-time, it may change',
    showQr : 'Show this QR to Service Provider',
    repositionMessageBookable1: "You have existing booking on ",
    repositionMessageBookable2: " for this queue ",
    repositionMessageBookable3: "You can select new slot for reposition ",
    repositionFifo1: "You have ",
    repositionFifo2: " for this queue ",
    repositionFifo3: "You can reposition by clicking join again",
    reposition: "Reposition",
    timeZone: "Asia/Calcutta",
    scale: "gregorian",
    download: "download",
    summary: "Booking confirmation from ",
    description: "Booking confirmation from ",
    confirmCancel: "Please confirm you want to cancel the booking with ",
    confirmReposition:
      "Please confirm you want to reposition the booking with ",
    successfullyCanceled: "Successfully canceled your booking with ",
    unableToCancel: "Unable to cancel your booking with ",
    queueOneDescription: "QueueOne Pages",
    queueOneAuthor: "YobnY Tech",
    pleaseWait: "Please wait..",
    details_of_person: "Details of Person ",
    booked_date: "Booked date",
    select: "Select ",
    services: "Services",
    manageBooking: "Manage positions",
    myPositions: "My positions",
    existingBooking: "You have existing booking from ",
    alreadyInTheQueue: "You are already joined",
    queueInactiveMessage:
      "Currently not accepting any joining requests, please try after sometime",
    suggestionMessage: "Please check below message",
    slotDay: "Day",
    error: "Error",
    position: "Position",
    SlotStartTime: "Start Time",
    SlotEndTime: "End Time",
    SlotType: "Type",
    Available: "Available",
    question_mark: " ?",
    skipQueue: "Shop with social distancing at your  favourite store",
    searchPlaceHodler: "Enter pincode or text to search the store",
    faqs: "FAQ's",
    myTokens: "My Bookings",
    refresh: "Refresh",
    errorMsg: "Oops.. that didnt work, please try again after some time",
    joinNextAvailableSlot: "Join Next Available Slot",
    availableBookableSlot: "Earliest slot available",
    notAvailable: "Not accepting booking",
    unSupportedBrowser: "Un-Supported Browser",
    toFar: "Very far from your location",
    selectDay: "Select Day",
    selectDate: "Select Date",
    available: "Available",
    cancel: "Cancel",
    close: "Close",
    BookingConfirmation: "Booking Confirmation from ",
    phone_auth_heading: "Please provide your phone number",
    requestOTP: "Validate Your Phone Number",
    requestOTPMessage:
      "Please enter your phone number here. You will receive OTP.",

    phone_auth_otp:
      "One-Time Password sent to your mobile, please verify to continue",
    phone_auth_placeholder: "+1 650787709 (+countrycode phonenumber)",
    phone_auth_login_err:
      "Invalid Phone Number, please provide in format [+countrycode phonenumber]",
    invalidPhone: "Invalid Phone Number, please provide a valid phone number",
    phone_auth_submit: "Submit",
    phone_auth_verify: "Verify",
    phone_auth_validate: "Validate",
    phone_auth_otp_password: "Enter OTP received",
    phone_auth_otp_error: "Invalid OTP",
    sugg_default_text:
      "Service is not accepting new position in the Queue, please contact the service provider",
    sugg_header: "Suggestion from Provider",
    sugg_cfa_ok: "Ok",
    prop_header: "To book your slot, please provide below details",
    prop_select_placeholder: "select the value",
    prop_cfa_submit: "Submit",
    prop_cfa_cancel: "Cancel",
    term_header: "Terms and Conditions",
    term_cfa_accept: "Accept",
    term_cfa_decline: "Decline",
    booked_slots_heading: "Booked Slot",
    booked_slots_direction: "Direction",
    booked_slot: "Slot",
    full: "Full",
    home: "Home",
    na: "N/A",
    today: "Today",
    select_staff: "Select Staff",
    tomorrow: "Tomorrow",
    totalVisting: "Total Number of Visitors",
    bookSlot: "Book Slot",
    join: "Join",
    allowAccess: "Please allow access to know your location",
    selectTime: "Select Time",
    morning: "MORNING",
    afternoon: "AFTERNOON",
    evening: "EVENING",
    noSlotsAvailable: "No slots available !",
    footerServiceOffered: "This service offered by QueueOne",
    footerCopyRight: "Technology Solutions.",
    footerCompayName: "YobnY",
    footerCopyRightYear: "2019",
    distanceApproximately: "Approximately ",
    distanceKms: " km from here",
    pleaseConfirm: "Please Confirm",
    servicesSelected: "Services Selected",
    selectedSlot: "Selected Booking Slot",
    detailsProvided: "Details Provided",
    introMessage:
      "Virtual Queuing System has been introduced, to reduce your wait time. You can join the Queue by selecting slot (if provided) and click the Book / Join Button",
    errorMsg1: "Unable to Book Slot : You have existing valid booking for [",
    errorMsg2: "No matching result for your search request",
    no_token: "You don't have any valid tokens, please get one",
    unableToJoin: "Unable to Book Slot, please try after some time",
    unableToGetPosition: "Unable to get a position, please try after some time",
    IAcceptTermsAndConditions: "I Accept Terms and Conditions",
    booking_confirm:
      "Great, we got your booking confirmed. Please present your QR Code.",
    joinWithBookingAndOTP: "Join with Booking and OTP",
    joinWithBookingAndOTPBasedOnGeoFence:
      "Join with Booking and OTP based on Geo-fence",
    joinWithBookingAndOTPBasedOnGeoFencingRadius:
      "Join with Booking and OTP based on Geo-fencing radius",
    joinWithBookingAndWithoutOTP: "Join with Booking and without OTP",
    joinWithBookingAndwithoutOTPBasedOnGeoFence:
      "Join with Booking and without OTP based on Geo-fence",
    joinWithBookingAndWithoutOTPBasedOnGeoFencingRadius:
      "Join with Booking and without OTP based on Geo-fencing radius",
    detailsHeading: "Your Details",
    serviceHeading: "Select Service",
    noAfternoonSlots: "No Afternoon slots available",
    noEveningSlots: "No Evening slots available",
    noMorningSlots: "No Morning slots available",
    morningSlots: "Morning slots",
    afternoonSlots: "Afternoon slots",
    eveningSlots: "Evening slots",
    selectSlots: "Select slots",
    noSlots: "No slots available",
    noStaffs: "No staff available",
    detailForPerson: "Details of Person",
    detailsDeleteTitle: "Are you sure want to delete?",
    detailsDeleteContent:
      "This will also delete any filled details on this form.",
    detailsRemoveUser: "Remove user",
    detailsAddAdditionaUser: "+ Add Additional Person Details",
    pleaseProvideRequiredDetails: "Please provide required details",
    pleaseSelectService: "Please select a service/s",
    pleaseSelectSlot: "Please select a slot",
    pleaseTryAgainLater: "Please try again later",
    noSlotsAvailableForDate:
      "No slots available for your selected date, Please select a different date!",
    pleaseSelectSlotAndDate: "Select Service Date and Slot",
    detailsAdd: "Add",
    valueYes: "Yes",
    valueNo: "No",
    confirm: "Confirm",
    footerCopyRights: "© 2021. All rights reserved",
    footerCaption: "Powered By Yobny Technology Solutions",
    socialFB: "FaceBook",
    socialGoogle: "Google",
    socialLinkedIn: "Linkedin",
    socialTwitter: "Twitter",
    queueOneErrorPage: "Queue not available",
    permissionDenied: "Permission denied",
    gettingGeoLocationInfo: "Getting location info...",
    phoneNumber: "Phone Number",
  },
});
export default queueStoreStrings;
